---

 - name: getting XDMoD CentOS 7 RPM
   yum: name=https://github.com/ubccr/xdmod/releases/download/v5.6.0/xdmod-5.6.0-1.0.el7.centos.noarch.rpm state=present

 - name: add super DB user
   mysql_user: name=admin password={{ xdmod_db_pass }} priv=*.*:ALL,GRANT state=present

 - name: enable httpd
   service: name=httpd enabled=yes

 - name: copy logo file
   copy: src=files/{{ xdmod_logofile_name }} dest=/etc/xdmod/{{ xdmod_logofile_name }} owner=root group=root mode=0644

 - name: generating configuration files (templates in the future)
   template: src=templates/{{ item }}.j2 dest=/etc/xdmod/{{ item }} owner=root group=root mode=0644
   with_items:
     - update_check.json
     - resource_specs.json
     - resources.json
     - organization.json
     - portal_settings.ini
   notify:
     - restart httpd

 - name: execute xdmod-slurm-helper command
   shell: /usr/bin/xdmod-slurm-helper -r {{ item.resource }}
   with_items: "{{ xdmod_resources }}"

 - name: create crontab entries for xdmod-slurm-helper
   cron: name="xdmod-slurm-helper" minute=0 hour={{ item.resource_type_id }}
        user="root" job="/usr/bin/xdmod-slurm-helper --quiet -r {{ item.resource }}"
        cron_file=xdmod
   with_items: "{{ xdmod_resources }}"

 - name: execute xdmod-ingestor command
   shell: /usr/bin/xdmod-ingestor -v

 - name: create crontab entries for xdmod-ingestor
   cron: name="xdmod-ingestor" minute=0 hour=7
        user="root" job="/usr/bin/xdmod-ingestor --quiet"
        cron_file=xdmod
